[project]
name = "capstone-sample"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Seu Nome", email = "seu.email@example.com" }
]
requires-python = ">=3.14"
dependencies = [
    "streamlit>=1.64.0",
]

[project.scripts]
capstone-sample = "capstone_sample:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
